# Generated by Django 3.2 on 2023-12-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chat_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='key',
            field=models.CharField(blank=True, editable=False, max_length=128),
        ),
    ]
