# Generated by Django 3.2 on 2023-12-05 10:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_user_user_friends_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
