# Generated by Django 3.2 on 2023-12-08 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_added',
        ),
    ]
