# Generated by Django 3.2 on 2023-12-08 10:02

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_user_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='images/avatar/user_img.png', upload_to=user.models.upload_avatar_path),
        ),
    ]
